version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: food-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: food-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/food_delivery
      - JWT_SECRET=supersecret
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: food-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  admin:
    build: ./admin
    container_name: food-admin
    ports:
      - "5174:80"
    depends_on:
      - backend

volumes:
  mongo_data:
