name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # === Backend ===
      - name: Build backend Docker image
        run: docker build -t food-backend:latest -f ./backend/Dockerfile ./backend

      # === Frontend ===
      - name: Build frontend Docker image
        run: docker build -t food-frontend:latest -f ./frontend/Dockerfile ./frontend

      # === Admin ===
      - name: Build admin Docker image
        run: docker build -t food-admin:latest -f ./admin/Dockerfile ./admin
